UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Aligner' WHERE type='Word aligner'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Language Modeling Tool' WHERE type='Language Modeling Toolkit'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Speech Recognizer/Transcriber' WHERE type='Speech recogniser'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Translation Tool' WHERE type='Machine Translation Toolkit'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Aligner' WHERE type='Word Alignment Tool'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Aligner' WHERE type='word aligner'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Aligner' WHERE type='Word Aligner'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Learning Tool' WHERE type='Machine Learning Classification Tool'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Translation Tool' WHERE type='Machine Translation software'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Tagger/Parser' WHERE type='Chunker'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Language Resources/Technologies Infrastructure' WHERE type='Language Processing Infrastructure'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Translation Tool' WHERE type='Machine Translator'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Aligner' WHERE type='Sentence aligner'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Language Modeling Tool' WHERE type='Language Model Tool'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Aligner' WHERE type='word-to-word aligner'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Learning Tool' WHERE type='Machine learning library'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Translation Tool' WHERE type='Machine Translation System'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Translation Tool' WHERE type='MT engine'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Translation Tool' WHERE type='Statistical Machine Translation system'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Translation Tool' WHERE type='Machine translation toolkit'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Translation Tool' WHERE type='Machine Translation tool'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Language Modeling Tool' WHERE type='Language model toolkit'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Learning Tool' WHERE type='Machine Learning Software'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Speech Recognizer/Transcriber' WHERE type='Automatic Speech Recognition tool'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Aligner' WHERE type='sentence alignment tool'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Translation Tool' WHERE type='Machine Translation'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Language Modeling Tool' WHERE type='Statsitical language modeling tool'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Language Modeling Tool' WHERE type='Language Modelling Toolkit'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Aligner' WHERE type='Unsupervised, Language Independent Sentence Aligner'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Language Resources/Technologies Infrastructure' WHERE type='language technology infrsatructure'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Learning Tool' WHERE type='Machine Learning API'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Translation Tool' WHERE type='Machine Translation toolkit'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Language Modeling Tool' WHERE type='language model toolkit'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Learning Tool' WHERE type='a software package for Support Vector Learning'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Learning Tool' WHERE type='Support Vector Machine Learning Tool'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Language Resources/Technologies Infrastructure' WHERE type='Node of Language Technology Infrastructure'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Aligner' WHERE type='Paragraph splitting and sentence alignment for parallel corpus'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Learning Tool' WHERE type='machine learning package'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Translation Tool' WHERE type='Statistical Machine Translation toolkit'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Language Modeling Tool' WHERE type='Language Modeling and Information Retrieval'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Translation Tool' WHERE type='Statistical machine translation'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Tagger/Parser' WHERE type='POS-tagger'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Machine Learning Tool' WHERE type='Machine learning software'; 
UPDATE TABLE  stage_lremap_resource_norm SET   type = 'Spoken Dialogue Tool' WHERE type='Spoken Dialogue Toolkit'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Representation-Annotation Standards/Best Practices' WHERE type='Representation-Annotation Standard/Best Practice'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Evaluation Methodology/Standards/Guidelines' WHERE type='Evaluation Methodology/Formalism/Guidelines'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Image Analyzer' WHERE type='Image Analyser'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Typological Database' WHERE type='Typological database'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Corpus Search Tool' WHERE type='Corpus search tool'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Terminological Database' WHERE type='terminological database'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Prosodic Analyzer' WHERE type='Prosodic Analyser'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Morphological Analyzer and Generator' WHERE type='morphological analyzer and generator'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Language Modeling Tool' WHERE type='Language modelling tool'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Search Engine' WHERE type='search engine'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Terminology Management System' WHERE type='Terminology management system'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Database' WHERE type='database'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Speaker Recognizer' WHERE type='Speaker recogniser'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Language Learning Tool' WHERE type='language learning tool'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'LRT Portal' WHERE type='LRT portal'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Semantic Associations' WHERE type='Semantic associations'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Translation Model' WHERE type='translation model'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Anaphora Resolution' WHERE type='Anaphora resolution'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Geoparsing Engine' WHERE type='A Geoparsing engine'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Corpus Query Tool' WHERE type='Corpus query tool'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Information Retrieval System' WHERE type='information retrieval system'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Word-level Semantic Similarities' WHERE type='Word-level semantic similarities'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Entity Mention Detection (EMD) Tool' WHERE type='Entity Mention Detection (EMD) tool'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Morphological Analyzer' WHERE type='Morphological analyzer'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Typological Database' WHERE type='Typological Database'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Relevant Term Extractor' WHERE type='Relevant Term extractor'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'NLP Architecture' WHERE type='NLP Architecture'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'WordNet' WHERE type='Wordnet'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Transliteration Similarity Estimation Software' WHERE type='Conversion tool for constituent-to-dependency conversion'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Ontology Development Methodology' WHERE type='Ontology development methodology'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Data Entry System' WHERE type='Data Entry System'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Resource: Morphology' WHERE type='Resource: morphology'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Text-to-Speech Synthesis Front End' WHERE type='Text-to-speech synthesis front end'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Psycholinguistic Database' WHERE type='Psycholinguistic Database'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Spelling Checker' WHERE type='Spelling Checker'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'APIs for Ontology Management' WHERE type='APIs for ontology management'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Text Simplification Tool' WHERE type='Text simplification tool'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Digital Library Management System' WHERE type='Digital library management system'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Adaptation System' WHERE type='Adaptation system'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Ontology Development Environment / Tool' WHERE type='Ontology Development Environment / Tool'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Resource: Encyclopedic Knowledge' WHERE type='Resource: encyclopedic knowledge'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Structure Search Engine/Annotation Data Repository' WHERE type='structure search engine/annotation data repository'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Search Engine' WHERE type='Serch Engine'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Corpus Interface' WHERE type='Corpus interface'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Machine Translation Toolkit' WHERE type='Machine translation toolkit'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Experiment data - collected' WHERE type='Experiement data - collected'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Morphological Analyzer' WHERE type='Morphological analyser'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Framework' WHERE type='framework'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'TIMEX Recognizer' WHERE type='TIMEX recognizer'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Software' WHERE type='software'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Concordancer' WHERE type='concordancer'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Statistical Language Modeling Tool' WHERE type='Statsitical language modeling tool'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Summarizer' WHERE type='summarizer'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Linguistic Pipeline Software' WHERE type='Linguistic pipeline software'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Natural Language Toolkit' WHERE type='natural language toolkit'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'SMT Decoder' WHERE type='SMT Decoder'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Sentence Splitter' WHERE type='Sentence splitter'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Educational Materials and Knowledge Dissemination' WHERE type='Educational materials and knowledge dissemination'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Morphological Analyzer' WHERE type='morphological analyser'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Corpus Analysis Software' WHERE type='Corpus analysis software'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Information Retrieval System' WHERE type='Information Retrieval system'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Text Editor' WHERE type='Text editor'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Spelling Corrector and OCR Post-Corrector' WHERE type='Spelling Corrector and OCR post-corrector'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Open-Search Engine Infrastructure' WHERE type='open-search engine infrastructure'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Searcher' WHERE type='searcher'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Web Service' WHERE type='webservice'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Open Source NLP Framework' WHERE type='Open source NLP framework'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Metadata Editor' WHERE type='Metadata editor'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Corpora Compilation and Evaluation' WHERE type='Corpora compilation and evaluation'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Language Technology Infrsatructure' WHERE type='language technology infrsatructure'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Finite State Tools' WHERE type='Finite state tools'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Cross-Lingual Information Retrieval Tool' WHERE type='Cross-Lingual Information Retrieval tool'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Tools for Accessing Knowledge Base' WHERE type='tools for accessing Knowledge base'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Grammar Customization System' WHERE type='Grammar customization system'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Term Extractor' WHERE type='term extractor'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Morphology Analyzer' WHERE type='Morphology analyzer'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Suite of NLP Tools' WHERE type='A suite of NLP tools'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Text-to-Speech Tool' WHERE type='Text-To-Speech tool'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Statistic Model Implementation' WHERE type='Statistic model implementation'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Lexicon/Corpus' WHERE type='Lexicon/corpus'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Machine Translation Toolkit' WHERE type='Machine Translation toolkit'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Question Answering System' WHERE type='Question Answering system'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'E-Learning' WHERE type='e-learning'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Terminology Service' WHERE type='Terminology service'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Language Modeling Tool' WHERE type='Lngugage modeling tool'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Semantic Registry' WHERE type='Semantic registry'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Ontological and Lexical Resource' WHERE type='Ontological and lexical resource'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Language Service Infrastructure' WHERE type='language service infrastructure'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Disordered Voice Synthesizer' WHERE type='Disordered voice synthesizer'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Format Conversion Scripts' WHERE type='format conversion scripts'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Keyphrase Extractor' WHERE type='keyphrase extractor'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Web Site' WHERE type='Web site'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Grammar Checker' WHERE type='Grammar checker'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'User Ratings' WHERE type='User ratings'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Rhetorical Structure Tagger' WHERE type='rhetorical structure tagger'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Annotation Tool, Search Engine' WHERE type='Annotation tool, search engine'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Search Engine' WHERE type='Search engine'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Phone Segmentation Tool' WHERE type='Phone segmentation tool'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Morphological Analyzer/Generator' WHERE type='Morphological analyzer/generator'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Morphological Analyzer' WHERE type='morphological analyzer'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Finite-State Compiler' WHERE type='finite-state compiler'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Acoustic and Language Models' WHERE type='Acoustic and language models'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Language Database' WHERE type='Language database'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Formal Grammar for Parser Generation' WHERE type='Formal grammar for parser generation'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Reasoner' WHERE type='Reasoner'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Monte-Carlo based Paraphrase Generator' WHERE type='Monte-Carlo based paraphrase generator'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Syntactic Judgments Database' WHERE type='A syntactic judgments database'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'General Purpose Language Engineering Platform' WHERE type='A general purpose langyage engineering platform'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Normalization Tool' WHERE type='Normalization tool'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Java Interface to Wikipedia' WHERE type='Java interface to Wikipedia'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Code Retrieval Models' WHERE type='Code retrieval models'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Data Mining  Toolkit' WHERE type='Data Mining  toolkit'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Anaphora Resolution Tool' WHERE type='Anaphora Resolutin Tool'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Search System' WHERE type='search system'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Automatic Summarization Tool' WHERE type='Automatic summarization tool'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'System for Lexical Acquisition' WHERE type='System for lexical acquisition'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Format Description' WHERE type='format description'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Automatic Syllable Segmentation Tool' WHERE type='automatic syllable segmentation tool'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Paraphrase Table' WHERE type='Paraphrase table'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Controlled Language Guidelines' WHERE type='Controlled Language guidelines'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Multimedia Language Learning Applications' WHERE type='Multimedia language learning applications'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'LSA Semantic Models' WHERE type='LSA semantic models'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Morphological Analyzer and Generator' WHERE type='Morphological analyzer and generator'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'English Morphological Analyzer' WHERE type='English Morphological Analyzer'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Statistical Decoder' WHERE type='Statistical decoder'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Speech Synthesizer' WHERE type='Speech synthesiser'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Statistical Signal Processing System' WHERE type='Statistical signal processing system'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Database Schema' WHERE type='Database schema'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Open Source System' WHERE type='open source system'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'SMT Toolkit' WHERE type='SMT toolkit'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Morphological Analyzer and Synthesizer' WHERE type='Morphological analyzer and synthesizer'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Morphological Analysis' WHERE type='Morphological analysis'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Lexicon Tools' WHERE type='Lexicon tools'; 
UPDATE TABLE  stage_lremap_resource SET   type = 'Conditional Random Fields (Crfs) Tagger' WHERE type='Conditional Random Fields (CRFs)  tagger'; 
